---
title: "Machine Learning Project - Cousera Week 4"
author: "Ridzuan Mohamad"
date: "5/11/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

## Data Exploratory Analysis

### Dataset Description

###Data Loading and Cleansing

```{r}
# set the URL for the download
url_train_data <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
url_test_test <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

# download the datasets
training <- read.csv(url(url_train_data))
testing <- read.csv(url(url_test_test))

dim(training)
dim(testing)
```

###Remove NA
```{r}
training.complete <- training[complete.cases(training),]
dim(training.complete)

testing.complete <- testing[complete.cases(testing),]
dim(testing.complete)
```

###Regressuion and Correlation Analysis

##Buidling Prediction Model

###Trainig Data

```{r}
# create partition 
#inTrain <- createDataPartition (training$classe, p=0.7, list=FALSE)
#TrainSet <- training[inTrain, ]
#TestSet <- training[-inTrain, ]
#dim(TrainSet)
```

###Random Forest

###Decision Trees


## Applying Model to Test Data
